include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact-name: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact-name: totem-right
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: totem_left_studio
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: totel_reset
# there is no settingsreset (needed) for the XIAO
